spring.datasource.url=jdbc:postgresql://localhost:12121/palletdb
spring.datasource.username=palletu
spring.datasource.password=palletpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e9f40f21ff3f87e5f37cc96af
app.jwt.expiration-ms=1800000

server.port=8080

logging.level.com.pallettruckwheels=DEBUG
